<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Sanare.Http.Tests</RootNamespace>
    <AssemblyName>Sanare.Http.Tests</AssemblyName>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Sanare.Browser\Sanare.Browser.csproj" />
    <ProjectReference Include="..\..\src\Sanare.Http\Sanare.Http.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="xunit.v3.mtp-v2" Version="4.0.1" />
    <PackageReference Include="Microsoft.Testing.Extensions.GitHubActionsReport" Version="2.4.1" />
    <PackageReference Include="PublicApiGenerator" Version="11.5.4" />
  </ItemGroup>

  <ItemGroup>
    <None Include="ApprovedApi\*.approved.txt" CopyToOutputDirectory="PreserveNewest" />
    <None Include="Data\**\*" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
