<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Sanare.Http.Tests</RootNamespace>
    <AssemblyName>Sanare.Http.Tests</AssemblyName>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Sanare.Http\Sanare.Http.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.12.0" />
    <PackageReference Include="xunit" Version="2.9.2" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.8.2" />
    <PackageReference Include="PublicApiGenerator" Version="11.5.4" />
  </ItemGroup>

  <ItemGroup>
    <None Include="ApprovedApi\*.approved.txt" CopyToOutputDirectory="PreserveNewest" />
    <None Include="Data\**\*" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
