<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Sanare.Core.Tests</RootNamespace>
    <AssemblyName>Sanare.Core.Tests</AssemblyName>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Sanare.Core\Sanare.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="xunit.v3.mtp-v2" Version="4.0.1" />
    <PackageReference Include="Microsoft.Testing.Extensions.GitHubActionsReport" Version="2.4.1" />
  </ItemGroup>

  <ItemGroup>
    <None Include="Fixtures\Data\**\*" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
